### ISSUE TITLE
text not lining correctly, creating a backdrop effect

### ISSUE THREAD

**Issue by leodesigndev** [wstaeblein/texthighlighter#2]
i came accross issue where i had highlight looking like the bellow 

![image](https://github.com/wstaeblein/texthighlighter/assets/56434221/c33ed00a-c9cf-47fb-9125-1b3ac0b6a2f2)

what helped to hide the issue is modifying/overwritting the .css so that i have

```css
.hlta-highlight mark {
    background-color: #00a1a1;
    color: rgba(0, 0, 0, 0);  /* <--- Help prevent offset introduced by target text area styling*/
}
```

1) can this be considered a proper fix , or what should the fix look like ?
